### ISSUE TITLE
Not an issue, a possible contribution...

### ISSUE THREAD

**Issue by yemling** [consbio/Leaflet.Geonames#12]
Hi there
I didn't know how to contact you directly.
Your geonames code is great, but we also need to be able to search by postcode. So I hope you don't mind but I've modified your code to search https://secure.geonames.org/postalCodeSearchJSON as well.
Would you like a copy?
Regards
Gemma

**Comment by brendan-ward** [comment]
@yemling We're glad this is useful for you.

A Pull Request with your changes would be the best way for us to consider how to add your changes into the plugin.  Would you be willing to submit one?

This is a great way to get in touch with us to discuss this issue.  Do you need direct contact info?

**Comment by yemling** [comment]
Thanks for getting back to me. 
I'm sorry, I'm pretty useless when it comes to github. If you can walk me through a pull request, then I'm more than happy to help.

**Comment by brendan-ward** [comment]
Resolved via PR some time ago
